#pragma once

#include <aiforge/surfaces/chat_session.hpp>
#include <variant>

namespace aiforge::surfaces {
inline constexpr std::size_t context_maximum_page_size = 16;
struct ContextInspect {
  std::string draft;
  std::size_t offset{};
  std::size_t limit{8};
};
struct ContextPolicy {
  std::uint64_t expected_revision{};
  domain::ConversationMode mode{};
  std::vector<domain::RunId> pins;
};
struct ContextPublish {
  domain::ConversationSummaryId summary_id;
};
struct ContextEdit {
  std::uint64_t expected_sequence{};
  domain::ConversationSummaryVersion parent;
  std::string text;
};
struct ContextPreview {
  domain::ConversationSummaryVersion candidate;
  std::vector<domain::ConversationSummaryVersion> replacements;
  std::string draft;
};
struct ContextPreviewPage {
  std::string handle;
  std::size_t offset{};
  std::size_t limit{context_maximum_page_size};
};
struct ContextApply {
  std::string handle;
  std::string draft;
};
struct ContextDisable {
  std::uint64_t expected_revision{};
  domain::ConversationSummaryVersion candidate;
  domain::EventId activation_event_id;
};
struct ContextClose {};
using ContextOperation =
    std::variant<ContextInspect, ContextPolicy, ChatSummaryGenerate,
                 ContextPublish, ContextEdit, ContextPreview,
                 ContextPreviewPage, ContextApply, ContextDisable,
                 ContextClose>;
struct ContextRequest {
  std::uint64_t id{};
  ContextOperation operation;
};
struct ContextOk {
  bool closed{};
};
struct ContextInspected {
  ChatConversationContextInspection context;
  ChatSummaryCatalog catalog;
  std::size_t offset{};
  std::size_t limit{};
};
struct ContextGenerated {
  domain::ConversationSummaryId summary_id;
  domain::RunId run_id;
};
struct ContextPreviewed {
  std::string handle;
  domain::ConversationSummaryActivation activation;
  domain::ConstructedContext context;
  std::uint64_t review_sequence{};
  std::size_t offset{};
  std::size_t limit{context_maximum_page_size};
};
struct ContextGenerationFinished {
  domain::ConversationSummaryId summary_id;
  domain::RunId run_id;
  domain::RunStatus status;
};
struct ContextFailure {
  std::string code;
  std::string message;
  bool effect_may_have_applied{};
};
using ContextPayload =
    std::variant<ContextOk, ContextInspected, ContextGenerated,
                 domain::ConversationSummaryCandidate, ContextPreviewed,
                 domain::ConversationSummaryActivation,
                 ContextGenerationFinished, ContextFailure>;
struct ContextReply {
  std::uint64_t id{};
  std::uint64_t sequence{};
  ContextPayload payload;
};

// Owns exactly one process-local review. The instance identity must be freshly
// generated by the process adapter; it is never a durable authorization token.
class ContextController final {
 public:
  ContextController(ChatSession& session, std::string instance_identity);
  [[nodiscard]] auto execute(const ContextRequest& request) -> ContextReply;
  [[nodiscard]] auto poll()
      -> std::expected<std::optional<ContextReply>, ChatSessionError>;
  [[nodiscard]] auto cancel_producer() -> std::expected<void, ChatSessionError>;
  [[nodiscard]] auto producer_active() const noexcept -> bool;
  [[nodiscard]] auto closed() const noexcept -> bool;

 private:
  [[nodiscard]] auto preview_page(const ContextPreviewPage& value)
      -> std::expected<ContextPayload, ChatSessionError>;
  [[nodiscard]] auto inspect(const ContextInspect& value)
      -> std::expected<ContextPayload, ChatSessionError>;
  [[nodiscard]] auto preview(const ContextPreview& value)
      -> std::expected<ContextPayload, ChatSessionError>;
  [[nodiscard]] auto apply(const ContextApply& value)
      -> std::expected<ContextPayload, ChatSessionError>;
  [[nodiscard]] auto dispatch(const ContextOperation& operation)
      -> std::expected<ContextPayload, ChatSessionError>;
  ChatSession& m_session;
  std::string m_instance_identity;
  std::uint64_t m_next_handle{};
  std::optional<ChatSummaryPreview> m_review;
  std::string m_review_handle;
  std::uint64_t m_review_sequence{};
  std::optional<ContextGenerated> m_producer;
  std::uint64_t m_producer_request_id{};
  bool m_closed{};
};
} // namespace aiforge::surfaces
